//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemRegistration.Model
{
    using System;
    using System.Collections.Generic;
    public partial class User
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string nick { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> data_birth { get; set; }
        public string password { get; set; }
        public string pass_repeat { get; set; }
        public string account { get; set; }
    }
}
